################################################################################
# Automatically-generated file. Do not edit!
################################################################################

S79_SRCS := 
OBJ_SRCS := 
S_SRCS := 
ASM_SRCS := 
C_SRCS := 
S79_UPPER_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
EXECUTABLES := 
OBJS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
. \
autogen \
brd4166a \
gecko_sdk_4.4.3/app/bluetooth/common/gatt_service_aio \
gecko_sdk_4.4.3/app/bluetooth/common/gatt_service_battery \
gecko_sdk_4.4.3/app/bluetooth/common/gatt_service_gas \
gecko_sdk_4.4.3/app/bluetooth/common/gatt_service_hall \
gecko_sdk_4.4.3/app/bluetooth/common/gatt_service_imu \
gecko_sdk_4.4.3/app/bluetooth/common/gatt_service_light \
gecko_sdk_4.4.3/app/bluetooth/common/gatt_service_pressure \
gecko_sdk_4.4.3/app/bluetooth/common/gatt_service_rgb \
gecko_sdk_4.4.3/app/bluetooth/common/gatt_service_rht \
gecko_sdk_4.4.3/app/bluetooth/common/gatt_service_sound \
gecko_sdk_4.4.3/app/bluetooth/common/in_place_ota_dfu \
gecko_sdk_4.4.3/app/bluetooth/common/power_supply \
gecko_sdk_4.4.3/app/bluetooth/common/sensor_gas \
gecko_sdk_4.4.3/app/bluetooth/common/sensor_hall \
gecko_sdk_4.4.3/app/bluetooth/common/sensor_imu \
gecko_sdk_4.4.3/app/bluetooth/common/sensor_light \
gecko_sdk_4.4.3/app/bluetooth/common/sensor_pressure \
gecko_sdk_4.4.3/app/bluetooth/common/sensor_rht \
gecko_sdk_4.4.3/app/bluetooth/common/sensor_select \
gecko_sdk_4.4.3/app/bluetooth/common/sensor_sound \
gecko_sdk_4.4.3/app/common/util/app_log \
gecko_sdk_4.4.3/app/common/util/app_timer \
gecko_sdk_4.4.3/hardware/board/src \
gecko_sdk_4.4.3/hardware/driver/bmp280/bosch/BMP280_driver \
gecko_sdk_4.4.3/hardware/driver/bmp280/src \
gecko_sdk_4.4.3/hardware/driver/ccs811/src \
gecko_sdk_4.4.3/hardware/driver/configuration_over_swo/src \
gecko_sdk_4.4.3/hardware/driver/icm20648/src \
gecko_sdk_4.4.3/hardware/driver/imu/src \
gecko_sdk_4.4.3/hardware/driver/mic/src \
gecko_sdk_4.4.3/hardware/driver/mx25_flash_shutdown/src/sl_mx25_flash_shutdown_usart \
gecko_sdk_4.4.3/hardware/driver/pressure/src \
gecko_sdk_4.4.3/hardware/driver/si1133/src \
gecko_sdk_4.4.3/hardware/driver/si70xx/src \
gecko_sdk_4.4.3/hardware/driver/si7210/src \
gecko_sdk_4.4.3/platform/Device/SiliconLabs/EFR32MG12P/Source \
gecko_sdk_4.4.3/platform/bootloader/api \
gecko_sdk_4.4.3/platform/bootloader/app_properties \
gecko_sdk_4.4.3/platform/common/src \
gecko_sdk_4.4.3/platform/common/toolchain/src \
gecko_sdk_4.4.3/platform/driver/button/src \
gecko_sdk_4.4.3/platform/driver/debug/src \
gecko_sdk_4.4.3/platform/driver/i2cspm/src \
gecko_sdk_4.4.3/platform/driver/leddrv/src \
gecko_sdk_4.4.3/platform/emdrv/dmadrv/src \
gecko_sdk_4.4.3/platform/emdrv/gpiointerrupt/src \
gecko_sdk_4.4.3/platform/emlib/src \
gecko_sdk_4.4.3/platform/radio/rail_lib/plugin/pa-conversions \
gecko_sdk_4.4.3/platform/radio/rail_lib/plugin/rail_util_power_manager_init \
gecko_sdk_4.4.3/platform/radio/rail_lib/plugin/rail_util_pti \
gecko_sdk_4.4.3/platform/security/sl_component/sl_mbedtls_support/src \
gecko_sdk_4.4.3/platform/security/sl_component/sl_protocol_crypto/src \
gecko_sdk_4.4.3/platform/security/sl_component/sl_psa_driver/src \
gecko_sdk_4.4.3/platform/service/device_init/src \
gecko_sdk_4.4.3/platform/service/iostream/src \
gecko_sdk_4.4.3/platform/service/mpu/src \
gecko_sdk_4.4.3/platform/service/power_manager/src \
gecko_sdk_4.4.3/platform/service/sleeptimer/src \
gecko_sdk_4.4.3/platform/service/system/src \
gecko_sdk_4.4.3/platform/service/udelay/src \
gecko_sdk_4.4.3/protocol/bluetooth/bgcommon/src \
gecko_sdk_4.4.3/protocol/bluetooth/lib/EFR32XG12/GCC \
gecko_sdk_4.4.3/protocol/bluetooth/src \
gecko_sdk_4.4.3/util/silicon_labs/silabs_core/memory_manager \
gecko_sdk_4.4.3/util/third_party/mbedtls/library \
gecko_sdk_4.4.3/util/third_party/printf \
gecko_sdk_4.4.3/util/third_party/printf/src \

