/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "sli_bt_gattdb_def.h"

extern const sli_bt_gattdb_t gattdb;

#define gattdb_generic_attribute              1
#define gattdb_service_changed_char           3
#define gattdb_database_hash                  6
#define gattdb_client_support_features        8
#define gattdb_device_name                    11
#define gattdb_device_information             14
#define gattdb_manufacturer_name_string       16
#define gattdb_model_number_string            18
#define gattdb_hardware_revision_string       20
#define gattdb_firmware_revision_string       22
#define gattdb_system_id                      24
#define gattdb_health_thermometer             25
#define gattdb_temperature_measurement        27
#define gattdb_temperature_type               30
#define gattdb_intermediate_temperature       32
#define gattdb_measurement_interval           35
#define gattdb_valid_range                    37
#define gattdb_ota                            38
#define gattdb_ota_control                    40


#endif // __GATT_DB_H
