/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "sli_bt_gattdb_def.h"

extern const sli_bt_gattdb_t gattdb;

#define gattdb_generic_attribute              1
#define gattdb_service_changed_char           3
#define gattdb_database_hash                  6
#define gattdb_client_support_features        8
#define gattdb_device_name                    11
#define gattdb_model_number_string            18
#define gattdb_hardware_revision_string       22
#define gattdb_firmware_revision_string       24
#define gattdb_system_id                      26
#define gattdb_iaq_eco2                       29
#define gattdb_iaq_tvoc                       31
#define gattdb_environment_sensing            32
#define gattdb_es_sound_level                 34
#define gattdb_es_pressure                    36
#define gattdb_es_temperature                 38
#define gattdb_es_humidity                    40
#define gattdb_es_uvindex                     42
#define gattdb_es_ambient_light               44
#define gattdb_hall_state                     47
#define gattdb_hall_field_strength            50
#define gattdb_hall_control_point             53
#define gattdb_automation_io                  54
#define gattdb_aio_digital_in                 56
#define gattdb_aio_num_of_digitals_in         59
#define gattdb_aio_digital_out                61
#define gattdb_aio_num_of_digitals_out        63
#define gattdb_ota                            64
#define gattdb_ota_control                    66
#define gattdb_ui_rgbleds                     69
#define gattdb_ui_rgbled_mask                 70
#define gattdb_battery_service                71
#define gattdb_batt_measurement               73
#define gattdb_power_source                   75
#define gattdb_power_source_type              77
#define gattdb_imu_acceleration               80
#define gattdb_imu_orientation                83
#define gattdb_imu_control_point              86


#endif // __GATT_DB_H
